# Generated by Django 2.2.10 on 2020-05-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0002_auto_20200309_1314"),
    ]

    operations = [
        migrations.RemoveField(model_name="tagslist", name="datasource",),
        migrations.DeleteModel(name="Tag",),
        migrations.DeleteModel(name="TagsList",),
    ]
