# Generated by Django 2.2.10 on 2020-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0004_auto_20200522_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instatefilter", name="field_type", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="instatefilter", name="filter_type", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(model_name="state", name="name", field=models.CharField(max_length=100),),
    ]
