# Generated by Django 2.2.10 on 2020-06-15 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0005_auto_20200527_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
