# Generated by Django 2.2.13 on 2020-10-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0007_auto_20200930_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statefilter",
            name="filter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_filters",
                to="datasources.Filter",
            ),
        ),
        migrations.AlterField(
            model_name="statefilter",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="filters", to="states.State"
            ),
        ),
    ]
