# Generated by Django 2.1.9 on 2019-10-14 13:08

from django.db import migrations, models
import schemacms.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_external_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', schemacms.users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Select an action from admin panel to change this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
