# Generated by Django 2.1.9 on 2019-10-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191014_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('undefined', 'undefined'), ('admin', 'admin'), ('editor', 'editor')], db_index=True, default='undefined', max_length=25),
        ),
    ]
