# Generated by Django 2.2.10 on 2020-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20191015_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="source",
            field=models.CharField(
                choices=[("undefined", "undefined"), ("auth0", "auth0"), ("okta", "okta")],
                default="undefined",
                max_length=16,
            ),
        ),
    ]
