# Generated by Django 2.2.13 on 2020-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20200831_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name="email address"),
        ),
    ]
