version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - echo install AWS CDK...
      - npm install -g aws-cdk
      - cdk --version
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Synchesize CDK stack...
      - cdk synth
artifacts:
  files:
    - 'cdk.out/**/*'
  name: cdk-out