version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - echo install AWS CDK...
      - npm install -g aws-cdk
      - cdk --version
      - pip install -r requirements.txt
      - VERSION=$(git describe --tags)
      - echo "Build version:$VERSION"
  build:
    commands:
      - echo Build started on `date`
      - echo Synchesize CDK stack...
      - cdk synth -c app_image_tag=$VERSION
artifacts:
  files:
    - 'cdk.out/**/*'
  name: cdk-out
cache:
  paths:
    - '/root/.npm/**/*'
    - '.env'