version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - echo install AWS CDK...
      - npm install -g aws-cdk@1.10.0
      - cdk --version
      - pip install -r requirements.txt
      - pip freeze
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION=${COMMIT_HASH:=latest}
      - echo "Build version:$VERSION"
  build:
    commands:
      - echo Build started on `date`
      - echo Build lambda function package
      - OLDPATH=$(pwd)
      - cd backend/functions/worker && npm install && sls package && rm -rf node_modules/
      - cd ${OLDPATH}
      - echo Synchesize CDK stack...
      - cdk synth -c app_image_tag=$VERSION
artifacts:
  files:
    - 'cdk.out/**/*'
  name: cdk-out
cache:
  paths:
    - '/root/.npm/**/*'
    - '.env'
