# Generated by Django 2.2.10 on 2020-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0002_datasourcetag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourcetag", name="value", field=models.CharField(max_length=150),
        ),
    ]
