# Generated by Django 2.2.10 on 2020-05-25 07:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0003_auto_20200522_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceDescription",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.jsonb.JSONField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "datasource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description",
                        to="datasources.DataSource",
                    ),
                ),
            ],
            options={"permissions": (("can_undelete", "Can undelete this object"),), "abstract": False},
        ),
    ]
