# Generated by Django 2.2.10 on 2020-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0004_datasourcedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource", name="name", field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wranglingscript", name="name", field=models.CharField(blank=True, max_length=100),
        ),
    ]
