# Generated by Django 2.2.10 on 2020-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0005_auto_20200527_0703"),
    ]

    operations = [
        migrations.AlterField(model_name="filter", name="name", field=models.CharField(max_length=100),),
    ]
