# Generated by Django 2.2.10 on 2020-08-21 12:33

import django.core.validators
from django.db import migrations, models
import schemacms.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0006_auto_20200603_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="google_sheet",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=schemacms.utils.models.file_upload_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["csv", "tsv"])],
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "file"),
                    ("database", "database"),
                    ("api", "api"),
                    ("google_sheet", "google sheet"),
                ],
                max_length=25,
            ),
        ),
    ]
