# Generated by Django 2.2.13 on 2020-10-06 14:53
from django.db import migrations, models, transaction


def set_job_is_active(apps, schema_editor):
    DataSource = apps.get_model("datasources", "DataSource")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        for datasource in DataSource.objects.using(db_alias).all():
            if datasource.active_job:
                active_job = datasource.active_job
                active_job.is_active = True
                active_job.save(update_fields=["is_active"])


def set_datasource_active_job(apps, schema_editor):
    Job = apps.get_model("datasources", "DataSourceJob")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        for job in Job.objects.using(db_alias).filter(is_active=True):
            job.datasource.active_job = job
            job.datasource.save(update_fields=["active_job"])


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0008_datasourcejob_result_parquet"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcejob", name="is_active", field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_job_is_active, set_datasource_active_job),
        migrations.RemoveField(model_name="datasource", name="active_job",),
    ]
