# Generated by Django 2.2.13 on 2021-06-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0010_datasourcemeta_fields_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='api_json_path',
            field=models.CharField(blank=True, default='', max_length=126),
        ),
        migrations.AddField(
            model_name='datasource',
            name='api_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='auto_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
