# Generated by Django 2.2.13 on 2021-06-15 08:00

from django.db import migrations, models, transaction


def get_jobs(jobs):
    for job in jobs:
        if job.datasource.type == "google_sheet":
            if not job.source_file_path:
                job.source_url = job.datasource.google_sheet
                job.source_file_path = f"{job.datasource_id}/uploads/google_sheet_source_file.csv"
                job.datasource_type = "google_sheet"
            else:
                job.datasource_type = "file"

        if job.datasource.type == "api":
            job.source_url = job.datasource.api_url
            job.datasource_type = "api"

        yield job


def get_ds(data_sources):
    for ds in data_sources:
        if ds.type == "api":
            ds.file = None
            ds.google_sheet = ""
        elif ds.type == "google_sheet":
            ds.api_url = ""
            ds.api_json_path = ""
            ds.file = None
            ds.auto_refresh = False
        else:
            ds.api_url = ""
            ds.api_json_path = ""
            ds.google_sheet = ""
            ds.auto_refresh = False

        yield ds


def updated_job_and_ds_fields(apps, schema_editor):
    Job = apps.get_model("datasources", "DataSourceJob")
    DataSource = apps.get_model("datasources", "DataSource")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        Job.objects.using(db_alias).bulk_update(
            get_jobs(Job.objects.using(db_alias).all().select_related("datasource")),
            ["datasource_type", "source_url", "source_file_path"],
        )

        DataSource.objects.using(db_alias).bulk_update(
            get_ds(DataSource.objects.using(db_alias).all()),
            ["file", "api_url", "api_json_path", "google_sheet", "auto_refresh"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0011_auto_20210610_0740"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcejob",
            name="datasource_type",
            field=models.CharField(
                choices=[
                    ("file", "file"),
                    ("database", "database"),
                    ("api", "api"),
                    ("google_sheet", "google sheet"),
                ],
                default="file",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="datasourcejob", name="source_url", field=models.URLField(blank=True, default=""),
        ),
        migrations.RunPython(updated_job_and_ds_fields, migrations.RunPython.noop),
    ]
