# Generated by Django 2.1.9 on 2019-09-03 07:31

from django.db import migrations, models
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190902_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemeta',
            name='preview',
            field=models.FileField(null=True, upload_to=schemacms.projects.models.file_upload_path),
        ),
    ]
