# Generated by Django 2.1.9 on 2019-09-03 13:28

from django.db import migrations, models
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20190902_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcemeta",
            name="preview",
            field=models.FileField(null=True, upload_to=schemacms.utils.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("processing", "processing"),
                    ("done", "done"),
                    ("error", "error"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
    ]
