# Generated by Django 2.1.9 on 2019-09-16 13:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190911_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', django_fsm.FSMField(choices=[('draft', 'draft'), ('ready_for_processing', 'ready for processing'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='draft', max_length=50)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='status',
        ),
        migrations.AddField(
            model_name='datasourcejob',
            name='datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.DataSource'),
        ),
    ]
