# Generated by Django 2.1.9 on 2019-09-19 08:59

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190911_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=django_fsm.FSMField(choices=[('in_progress', 'in progress'), ('done', 'done'), ('hold', 'hold'), ('published', 'published')], default='in_progress', max_length=50),
        ),
    ]
