# Generated by Django 2.1.9 on 2019-09-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_datasourcejob'),
        ('projects', '0009_auto_20190919_0859'),
    ]

    operations = [
    ]
