# Generated by Django 2.1.9 on 2019-09-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20190919_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceJobStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('exec_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasourcejob',
            name='scripts_ref',
        ),
        migrations.RemoveField(
            model_name='datasourcejob',
            name='steps',
        ),
        migrations.AddField(
            model_name='datasourcejobstep',
            name='datasource_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.DataSourceJob'),
        ),
    ]
