# Generated by Django 2.1.9 on 2019-10-01 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20190919_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='WranglingScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('is_predefined', models.BooleanField(default=True)),
                ('file', models.FileField(null=True, upload_to='scripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])])),
                ('body', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='projects.DataSource')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datasourcejob',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='datasourcejobstep',
            name='key',
        ),
        migrations.AddField(
            model_name='datasourcejob',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasourcejob',
            name='result',
            field=models.FileField(null=True, upload_to=schemacms.projects.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='datasourcejobstep',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasourcejobstep',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.WranglingScript'),
        ),
    ]
