# Generated by Django 2.1.9 on 2019-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191001_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='wranglingscript',
            name='last_file_modification',
            field=models.DateTimeField(null=True),
        ),
    ]
