# Generated by Django 2.1.9 on 2019-09-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190927_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wranglingscript',
            name='datasource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='projects.DataSource'),
        ),
    ]
