# Generated by Django 2.1.9 on 2019-10-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_wranglingscript_last_file_modification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('-created',)},
        ),
    ]
