# Generated by Django 2.1.9 on 2019-10-04 09:27

from django.db import migrations, models
import django.db.models.deletion
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_auto_20191003_1009"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceJobMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("items", models.PositiveIntegerField()),
                ("fields", models.PositiveSmallIntegerField()),
                ("preview", models.FileField(null=True, upload_to=schemacms.utils.models.file_upload_path)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_data",
                        to="projects.DataSourceJob",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
