# Generated by Django 2.1.9 on 2019-10-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20191016_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='status',
        ),
    ]
