# Generated by Django 2.1.9 on 2019-10-22 11:14

import django.core.validators
from django.db import migrations, models
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_datasource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wranglingscript',
            name='file',
            field=models.FileField(null=True, upload_to=schemacms.projects.models.file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
    ]
