# Generated by Django 2.1.9 on 2019-10-22 14:25

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20191022_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcejob',
            name='job_state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=50),
        ),
    ]
