# Generated by Django 2.1.9 on 2019-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_datasourcejob_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcejob',
            name='source_file_path',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcejob',
            name='source_file_version',
            field=models.CharField(default='', editable=False, max_length=36),
            preserve_default=False,
        ),
    ]
