# Generated by Django 2.1.9 on 2019-10-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('projects', '0023_project_deleted_at')]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('radio_button', 'Radio Button'),
                            ('checkbox', 'Checkbox'),
                            ('calendar', 'Calendar'),
                        ],
                        max_length=25,
                    ),
                ),
                ('field', models.CharField(max_length=25)),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('text', 'Text'),
                            ('date', 'Date'),
                            ('boolean', 'Boolean'),
                            ('number', 'Bumber'),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    'datasource',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='filters',
                        to='projects.DataSource',
                    ),
                ),
            ],
        )
    ]
