# Generated by Django 2.1.9 on 2019-11-04 13:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [('projects', '0023_project_deleted_at')]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=25)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('radio_button', 'Radio Button'),
                            ('checkbox', 'Checkbox'),
                            ('calendar', 'Calendar'),
                        ],
                        max_length=25,
                    ),
                ),
                ('field', models.CharField(max_length=25)),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('string', 'String'),
                            ('date', 'Date'),
                            ('boolean', 'Boolean'),
                            ('number', 'Number'),
                        ],
                        max_length=25,
                    ),
                ),
                ('unique_items', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'datasource',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='filters',
                        to='projects.DataSource',
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(name='filter', unique_together={('name', 'datasource')}),
    ]
