# Generated by Django 2.1.9 on 2019-11-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('projects', '0024_filter')]

    operations = [migrations.AlterUniqueTogether(name='filter', unique_together={('name', 'datasource')})]
