# Generated by Django 2.1.9 on 2019-11-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('projects', '0024_auto_20191104_1323')]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='active_job',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='data_sources',
                to='projects.DataSourceJob',
            ),
        )
    ]
