# Generated by Django 2.1.9 on 2019-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('projects', '0025_datasource_active_job')]

    operations = [
        migrations.AlterField(
            model_name='wranglingscript', name='name', field=models.CharField(blank=True, max_length=50)
        )
    ]
