# Generated by Django 2.1.9 on 2019-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('projects', '0025_datasource_active_job')]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(
                choices=[
                    ('Calendar', 'CALENDAR'),
                    ('Time Input', 'TIME_INPUT'),
                    ('Time Scrubber', 'TIME_SCRUBBER'),
                    ('Switch', 'SWITCH'),
                    ('Cartogram', 'CARTOGRAM'),
                    ('Zipcode Input', 'ZIPCODE_INPUT'),
                    ('Radio Button', 'RADIO_BUTTON'),
                    ('Checkbox', 'CHECKBOX'),
                    ('Search Input', 'SEARCH_INPUT'),
                    ('Tags', 'TAGS'),
                    ('Interval Slider', 'INTERVAL_SLIDER'),
                    ('Single Point Slider', 'SINGLE_POINT_SLIDER'),
                ],
                max_length=25,
            ),
        )
    ]
