# Generated by Django 2.1.9 on 2019-11-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('projects', '0026_auto_20191106_1301')]

    operations = [migrations.RenameField(model_name='filter', old_name='type', new_name='filter_type')]
