# Generated by Django 2.1.9 on 2019-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('projects', '0026_auto_20191106_1019'), ('projects', '0027_auto_20191106_1301')]

    operations = []
