# Generated by Django 2.1.9 on 2019-11-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('projects', '0028_merge_20191106_1419')]

    operations = [
        migrations.AlterField(
            model_name='wranglingscript',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scripts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='wranglingscript',
            name='datasource',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scripts',
                to='projects.DataSource',
            ),
        ),
    ]
