# Generated by Django 2.1.9 on 2019-11-18 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20191112_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcejobstep',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
