# Generated by Django 2.1.9 on 2019-11-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0032_auto_20191121_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from='title', verbose_name='slug'
                    ),
                ),
                ('keywords', models.TextField(blank=True, default='')),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'directory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pages',
                        to='projects.Directory',
                    ),
                ),
            ],
            options={'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(name='page', unique_together={('title', 'directory')},),
    ]
