# Generated by Django 2.1.9 on 2019-11-25 09:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import schemacms.projects.models
import schemacms.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20191122_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=25)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('youtube_embed', 'Youtube Embed'),
                            ('code_snippet', 'Code Snippet'),
                            ('markdown_text', 'Markdown Text'),
                            ('image_uploaded', 'Image Uploaded'),
                        ],
                        max_length=25,
                    ),
                ),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(null=True, upload_to=schemacms.projects.models.file_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.Page'
                    ),
                ),
            ],
            options={'ordering': ('created',)},
            bases=(schemacms.utils.models.MetaGeneratorMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(name='block', unique_together={('name', 'page')},),
    ]
