# Generated by Django 2.1.9 on 2019-11-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20191125_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={
                'ordering': ('name',),
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
            },
        ),
    ]
