# Generated by Django 2.1.9 on 2019-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20191125_1341'),
    ]

    operations = [
        migrations.AlterField(model_name='block', name='name', field=models.CharField(max_length=50),),
        migrations.AlterField(
            model_name='datasource', name='name', field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(model_name='directory', name='name', field=models.CharField(max_length=50),),
    ]
