# Generated by Django 2.1.9 on 2019-11-29 07:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20191125_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcejobstep',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
