# Generated by Django 2.1.9 on 2019-12-02 08:59

from django.db import migrations, models
import schemacms.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_auto_20191129_0730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourcejob",
            name="result",
            field=models.FileField(blank=True, null=True, upload_to=schemacms.utils.models.file_upload_path),
        ),
    ]
