# Generated by Django 2.1.9 on 2019-12-02 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20191202_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='wranglingscript',
            name='specs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
