# Generated by Django 2.2.8 on 2019-12-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20191211_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(name='datasource', options={'ordering': ('-modified',)},),
    ]
