# Generated by Django 2.2.8 on 2019-12-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20191212_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(name='blockimage', options={'ordering': ('created',)},),
    ]
