# Generated by Django 2.2.8 on 2019-12-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20191216_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemeta', name='error', field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasourcemeta',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Success'),
                ],
                default='pending',
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='datasourcejobmetadata',
            name='fields',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datasourcejobmetadata', name='items', field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datasourcejobstep',
            name='script',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='steps',
                to='projects.WranglingScript',
            ),
        ),
        migrations.AlterField(
            model_name='datasourcemeta', name='fields', field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datasourcemeta', name='items', field=models.PositiveIntegerField(null=True),
        ),
    ]
