# Generated by Django 2.2.8 on 2019-12-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_set_meta_data_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='active_job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='data_sources',
                to='projects.DataSourceJob',
            ),
        ),
    ]
