# Generated by Django 2.2.8 on 2020-01-08 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20191227_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcejobmetadata',
            name='fields_with_urls',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name='datasourcemeta',
            name='fields_with_urls',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, default=list, size=None
            ),
        ),
    ]
