# Generated by Django 2.2.8 on 2020-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20200113_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='block', name='exec_order', field=models.IntegerField(default=None, null=True),
        ),
    ]
