# Generated by Django 2.2.8 on 2020-01-24 16:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import schemacms.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_block_exec_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('key', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'datasource',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to='projects.DataSource',
                    ),
                ),
            ],
            options={'ordering': ('created',)},
            bases=(schemacms.utils.models.MetaGeneratorMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None), fields=('datasource', 'key'), name='unique_tag_key'
            ),
        ),
    ]
