# Generated by Django 2.2.8 on 2020-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20200128_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(
                choices=[
                    ('video', 'Video'),
                    ('code', 'Code'),
                    ('markdown', 'Markdown'),
                    ('text', 'Text'),
                    ('image', 'Image'),
                ],
                max_length=25,
            ),
        ),
    ]
