# Generated by Django 2.2.8 on 2020-01-28 11:20

from django.db import migrations, models, transaction


def old_type_to_new(apps, schema_editor):
    Block = apps.get_model("projects", "Block")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        Block.objects.using(db_alias).filter(type="youtube_embed").update(type="embed")
        Block.objects.using(db_alias).filter(type="code_snippet").update(type="code")
        Block.objects.using(db_alias).filter(type="markdown_text").update(type="markdown")
        Block.objects.using(db_alias).filter(type="image_uploaded").update(type="image")


def reverse_func(apps, schema_editor):
    Block = apps.get_model("projects", "Block")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        Block.objects.using(db_alias).filter(type="embed").update(type="youtube_embed")
        Block.objects.using(db_alias).filter(type="code").update(type="code_snippet")
        Block.objects.using(db_alias).filter(type__in=["markdown", "text"]).update(type="markdown_text")
        Block.objects.using(db_alias).filter(type="image").update(type="image_uploaded")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_auto_20200128_0759"),
    ]

    operations = [
        migrations.RunPython(old_type_to_new, reverse_func),
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("embed", "Embed"),
                    ("code", "Code"),
                    ("markdown", "Markdown"),
                    ("text", "Text"),
                    ("image", "Image Upload"),
                ],
                max_length=25,
            ),
        ),
    ]
