# Generated by Django 2.2.8 on 2020-02-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20200129_1115'),
    ]

    operations = [
        migrations.DeleteModel(name='Tag'),
    ]
