# Generated by Django 2.2.8 on 2020-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20200129_1157'),
    ]

    operations = [
        migrations.AddField(model_name='tag', name='exec_order', field=models.IntegerField(default=0),),
    ]
