# Generated by Django 2.2.8 on 2020-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_tag_tagslist'),
    ]

    operations = [
        migrations.AlterModelOptions(name='tagslist', options={'ordering': ('created',)},),
        migrations.AddConstraint(
            model_name='tagslist',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=('datasource', 'name'),
                name='unique_tags_list_name',
            ),
        ),
    ]
