# Generated by Django 2.2.8 on 2020-02-07 07:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20200206_0911'),
    ]

    operations = [
        migrations.RemoveField(model_name='instatefilter', name='condition_values',),
        migrations.AddField(
            model_name='instatefilter',
            name='condition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
