# Generated by Django 2.2.8 on 2020-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20200207_0748'),
    ]

    operations = [
        migrations.AlterField(model_name='filter', name='field', field=models.TextField(),),
    ]
