# Generated by Django 2.2.8 on 2020-02-10 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20200210_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcejobmetadata',
            name='fields_names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name='datasourcejobmetadata',
            name='fields_with_urls',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name='datasourcemeta',
            name='fields_names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name='datasourcemeta',
            name='fields_with_urls',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
