# Generated by Django 2.2.8 on 2020-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20200210_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='field_type',
            field=models.CharField(
                choices=[
                    ('string', 'String'),
                    ('datetime', 'Date/Time'),
                    ('boolean', 'Boolean'),
                    ('number', 'Number'),
                ],
                max_length=25,
            ),
        ),
    ]
