# Generated by Django 2.2.10 on 2020-02-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0067_auto_20200210_1500"),
    ]

    operations = [
        migrations.RemoveField(model_name="state", name="author",),
        migrations.RemoveField(model_name="state", name="datasource",),
        migrations.RemoveField(model_name="state", name="filters",),
        migrations.RemoveField(model_name="state", name="project",),
        migrations.RemoveField(model_name="tag", name="tags_list",),
        migrations.RemoveField(model_name="tagslist", name="datasource",),
        migrations.DeleteModel(name="InStateFilter",),
        migrations.DeleteModel(name="State",),
        migrations.DeleteModel(name="Tag",),
        migrations.DeleteModel(name="TagsList",),
    ]
