# Generated by Django 2.2.10 on 2020-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0070_auto_20200227_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="domain", field=models.URLField(blank=True, default=""),
        ),
    ]
