# Generated by Django 2.2.10 on 2020-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_auto_20200304_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktemplate", name="allow_add", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blocktemplate", name="is_available", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagetemplate", name="allow_add", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagetemplate", name="is_available", field=models.BooleanField(default=False),
        ),
    ]
