# Generated by Django 2.2.10 on 2020-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_auto_20200306_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetemplate",
            name="blocks",
            field=models.ManyToManyField(blank=True, related_name="page_templates", to="pages.BlockTemplate"),
        ),
    ]
