# Generated by Django 2.2.10 on 2020-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_auto_20200309_1203"),
    ]

    operations = [
        migrations.RemoveField(model_name="pagetemplate", name="blocks",),
        migrations.AddField(
            model_name="blocktemplateelement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
