# Generated by Django 2.2.10 on 2020-03-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_auto_20200313_0812"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplateBlock",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "block_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.BlockTemplate"),
                ),
                (
                    "page_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.PageTemplate"),
                ),
            ],
            options={"permissions": (("can_undelete", "Can undelete this object"),), "abstract": False},
        ),
        migrations.AddField(
            model_name="pagetemplate",
            name="blocks",
            field=models.ManyToManyField(through="pages.PageTemplateBlock", to="pages.BlockTemplate"),
        ),
    ]
