# Generated by Django 2.2.10 on 2020-03-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_auto_20200313_0954"),
    ]

    operations = [
        migrations.RenameModel(old_name="BlockTemplateElement", new_name="BlockElement",),
        migrations.RenameModel(old_name="BlockTemplate", new_name="Block",),
        migrations.RenameModel(old_name="PageTemplate", new_name="Page",),
        migrations.RenameModel(old_name="PageTemplateBlock", new_name="PageBlock",),
    ]
