# Generated by Django 2.2.10 on 2020-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_auto_20200315_1457"),
    ]

    operations = [
        migrations.AlterModelOptions(name="pageblock", options={},),
        migrations.RenameField(model_name="pageblock", old_name="block_template", new_name="block",),
        migrations.RenameField(model_name="pageblock", old_name="page_template", new_name="page",),
        migrations.RemoveField(model_name="pageblock", name="deleted_at",),
        migrations.AddField(model_name="block", name="is_template", field=models.BooleanField(default=True),),
        migrations.AddField(model_name="page", name="is_template", field=models.BooleanField(default=True),),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=("project", "name", "is_template"),
                name="unique_block_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=("project", "name", "is_template"),
                name="unique_page_name",
            ),
        ),
    ]
