# Generated by Django 2.2.10 on 2020-03-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_section_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="page", name="description", field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="page",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AddField(
            model_name="page", name="keywords", field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="page",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="pages.Section",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="template",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.Page"),
        ),
    ]
