# Generated by Django 2.2.10 on 2020-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_page_slug"),
    ]

    operations = [
        migrations.AddField(model_name="page", name="is_public", field=models.BooleanField(default=False),),
    ]
