# Generated by Django 2.2.10 on 2020-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_page_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageblock", options={"permissions": (("can_undelete", "Can undelete this object"),)},
        ),
        migrations.AddField(
            model_name="pageblock",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
