# Generated by Django 2.2.10 on 2020-03-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_auto_20200319_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplate",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("pages.page",),
        ),
    ]
