# Generated by Django 2.2.10 on 2020-03-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_pagetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="template",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.PageTemplate"
            ),
        ),
    ]
