# Generated by Django 2.2.10 on 2020-04-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_pageblockelement"),
    ]

    operations = [
        migrations.RenameField(model_name="page", old_name="allow_add", new_name="allow_edit",),
        migrations.RemoveField(model_name="block", name="allow_add",),
    ]
