# Generated by Django 2.2.10 on 2020-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_auto_20200402_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblockelement",
            name="code",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="plain_text",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="rich_text",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
