# Generated by Django 2.2.10 on 2020-04-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_auto_20200407_1101"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="page", name="unique_page_name",),
    ]
