# Generated by Django 2.2.10 on 2020-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_auto_20200409_1054"),
    ]

    operations = [
        migrations.RemoveField(model_name="pageblockelement", name="rich_text",),
        migrations.AddField(
            model_name="pageblockelement", name="markdown", field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="blockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("stack", "Stack"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="connection",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("stack", "Stack"),
                ],
                max_length=25,
            ),
        ),
    ]
