# Generated by Django 2.2.10 on 2020-04-15 10:42

from django.db import migrations, models, transaction
from ..constants import ElementType


def old_type_to_new(apps, schema_editor):
    block_element = apps.get_model("pages", "BlockElement")
    page_block_element = apps.get_model("pages", "PageBlockElement")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        block_element.objects.using(db_alias).filter(type="rich_text").update(type=ElementType.MARKDOWN)
        page_block_element.objects.using(db_alias).filter(type="rich_text").update(type=ElementType.MARKDOWN)


def reverse_func(apps, schema_editor):
    block_element = apps.get_model("pages", "BlockElement")
    page_block_element = apps.get_model("pages", "PageBlockElement")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        block_element.objects.using(db_alias).filter(type="markdown").update(type="rich_text")
        page_block_element.objects.using(db_alias).filter(type="markdown").update(type="rich_text")


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_auto_20200409_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblockelement", name="rich_text", field=models.TextField(blank=True, default=""),
        ),
        migrations.RenameField(model_name="pageblockelement", old_name="rich_text", new_name="markdown",),
        migrations.AlterField(
            model_name="blockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("stack", "Stack"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="connection",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("stack", "Stack"),
                ],
                max_length=25,
            ),
        ),
        migrations.RunPython(old_type_to_new, reverse_func),
    ]
