# Generated by Django 2.2.10 on 2020-04-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_auto_20200416_0845"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="main_page",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_page",
                to="pages.Page",
            ),
        ),
    ]
