# Generated by Django 2.2.10 on 2020-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_section_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblockelement',
            name='internal_connection',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockelement',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain_text', 'Plain Text'), ('image', 'Image'), ('code', 'Code'), ('connection', 'Connection'), ('internal_connection', 'Internal Connection')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pageblockelement',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain_text', 'Plain Text'), ('image', 'Image'), ('code', 'Code'), ('connection', 'Connection'), ('internal_connection', 'Internal Connection')], max_length=25),
        ),
    ]
