# Generated by Django 2.2.10 on 2020-04-27 07:42

from django.db import migrations, models
import django.db.models.deletion
import schemacms.utils.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200421_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblockelement',
            name='image',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=None), upload_to=schemacms.utils.models.file_upload_path),
        ),
        migrations.CreateModel(
            name='PageBlockObservableElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('observableUser', models.TextField(blank=True, default='')),
                ('observableNotebook', models.TextField(blank=True, default='')),
                ('observableCell', models.TextField(blank=True, default='')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockElement', to='pages.PageBlockElement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
