# Generated by Django 2.2.10 on 2020-04-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_auto_20200421_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("internal_connection", "Internal Connection"),
                    ("custom_element", "Custom Element"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("internal_connection", "Internal Connection"),
                    ("custom_element", "Custom Element"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="PageCustomElement",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_elements",
                        to="pages.PageBlockElement",
                    ),
                ),
            ],
            options={"permissions": (("can_undelete", "Can undelete this object"),), "abstract": False},
        ),
        migrations.AddField(
            model_name="pageblockelement",
            name="custom_element",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="pages.PageCustomElement",
            ),
        ),
    ]
