# Generated by Django 2.2.10 on 2020-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200427_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockelement',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain_text', 'Plain Text'), ('image', 'Image'), ('code', 'Code'), ('connection', 'Connection'), ('internal_connection', 'Internal Connection'), ('observable_hq', 'ObservableHQ')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pageblockelement',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain_text', 'Plain Text'), ('image', 'Image'), ('code', 'Code'), ('connection', 'Connection'), ('internal_connection', 'Internal Connection'), ('observable_hq', 'ObservableHQ')], max_length=25),
        ),
    ]
