# Generated by Django 2.2.10 on 2020-04-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_auto_20200427_1129"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageBlockObservableElement",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("observable_user", models.TextField(blank=True, default="")),
                ("observable_notebook", models.TextField(blank=True, default="")),
                ("observable_cell", models.TextField(blank=True, default="")),
            ],
            options={"permissions": (("can_undelete", "Can undelete this object"),), "abstract": False},
        ),
        migrations.AlterField(
            model_name="blockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("internal_connection", "Internal Connection"),
                    ("observable_hq", "ObservableHQ"),
                    ("custom_element", "Custom Element"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("plain_text", "Plain Text"),
                    ("image", "Image"),
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("internal_connection", "Internal Connection"),
                    ("observable_hq", "ObservableHQ"),
                    ("custom_element", "Custom Element"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="pageblockelement",
            name="observable_hq",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_element",
                to="pages.PageBlockObservableElement",
            ),
        ),
    ]
