# Generated by Django 2.2.10 on 2020-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200428_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblockobservableelement',
            name='observable_params',
            field=models.TextField(blank=True, default=''),
        ),
    ]
