# Generated by Django 2.2.10 on 2020-04-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200427_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageblockobservableelement',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
    ]
