# Generated by Django 2.2.10 on 2020-05-04 08:34

from django.db import migrations, models
import schemacms.utils.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200428_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblockobservableelement',
            name='observable_params',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pageblockelement',
            name='image',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=None), upload_to=schemacms.utils.models.file_upload_path),
        ),
    ]
