# Generated by Django 2.2.10 on 2020-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_pageblockobservableelement_observable_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblockobservableelement',
            name='observable_cell',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pageblockobservableelement',
            name='observable_notebook',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pageblockobservableelement',
            name='observable_params',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pageblockobservableelement',
            name='observable_user',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
