# Generated by Django 2.2.10 on 2020-04-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200427_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblockobservableelement',
            name='element',
        ),
        migrations.AddField(
            model_name='pageblockelement',
            name='observable_hq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_element', to='pages.PageBlockObservableElement'),
        ),
    ]
