# Generated by Django 2.2.10 on 2020-05-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0030_auto_20200504_1205"),
    ]

    operations = [
        migrations.RemoveField(model_name="pageblockelement", name="custom_element",),
        migrations.CreateModel(
            name="CustomElementSet",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "custom_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements_sets",
                        to="pages.PageBlockElement",
                    ),
                ),
            ],
            options={"permissions": (("can_undelete", "Can undelete this object"),), "abstract": False},
        ),
        migrations.AddField(
            model_name="pageblockelement",
            name="custom_element_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="pages.CustomElementSet",
            ),
        ),
    ]
