# Generated by Django 2.2.10 on 2020-05-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0071_project_domain"),
        ("pages", "0030_auto_20200504_1205"),
    ]

    operations = [
        migrations.RenameModel("block", "blocktemplate"),
        migrations.AlterField(
            model_name="blockelement",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="elements", to="pages.BlockTemplate"
            ),
        ),
        migrations.RemoveField(model_name="blocktemplate", name="is_template"),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(through="pages.PageBlock", to="pages.BlockTemplate"),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.BlockTemplate"),
        ),
        migrations.AddConstraint(
            model_name="blocktemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=("project", "name"),
                name="unique_block_template_name",
            ),
        ),
    ]
