# Generated by Django 2.2.10 on 2020-05-07 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0071_project_domain"),
        ("pages", "0031_auto_20200506_1217"),
    ]

    operations = [
        migrations.RenameModel(old_name="Block", new_name="BlockTemplate",),
        migrations.AlterField(
            model_name="blockelement",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="elements", to="pages.BlockTemplate"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(through="pages.PageBlock", to="pages.BlockTemplate"),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.BlockTemplate"),
        ),
        migrations.RenameModel(old_name="BlockElement", new_name="BlockTemplateElement",),
        migrations.RemoveConstraint(model_name="blocktemplate", name="unique_block_name",),
        migrations.AddConstraint(
            model_name="blocktemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=("project", "name"),
                name="unique_block_template_name",
            ),
        ),
    ]
