# Generated by Django 2.2.10 on 2020-05-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_auto_20200505_1321"),
    ]

    operations = [
        migrations.RenameModel(old_name="BlockElement", new_name="BlockTemplateElement",),
        migrations.RemoveConstraint(model_name="blocktemplate", name="unique_block_name",),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="elements", to="pages.BlockTemplate"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(through="pages.PageBlock", to="pages.BlockTemplate"),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.BlockTemplate"),
        ),
    ]
