# Generated by Django 2.2.10 on 2020-05-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_auto_20200507_0953"),
    ]

    operations = [
        migrations.RemoveField(model_name="blocktemplate", name="is_template",),
    ]
