# Generated by Django 2.2.10 on 2020-05-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_pagetag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblock",
            name="block",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.BlockTemplate"
            ),
        ),
    ]
