# Generated by Django 2.2.10 on 2020-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_auto_20200525_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktemplate", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="page",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(model_name="page", name="name", field=models.CharField(max_length=100),),
        migrations.AlterField(model_name="pageblock", name="name", field=models.CharField(max_length=100),),
        migrations.AlterField(
            model_name="pageblockelement",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(model_name="section", name="name", field=models.CharField(max_length=100),),
    ]
