# Generated by Django 2.2.10 on 2020-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0038_auto_20200527_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblockelement",
            name="video",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("video", "Video"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("video", "Video"),
                ],
                max_length=25,
            ),
        ),
    ]
