# Generated by Django 2.2.10 on 2020-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0039_auto_20200527_1132"),
    ]

    operations = [
        migrations.RenameField(model_name="pageblockelement", old_name="video", new_name="embed_video",),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("embed_video", "Embed Video"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("embed_video", "Embed Video"),
                ],
                max_length=25,
            ),
        ),
    ]
