# Generated by Django 2.2.10 on 2020-06-08 06:49

from django.db import migrations, models
import schemacms.utils.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0040_auto_20200604_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblockelement",
            name="file",
            field=models.FileField(
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(bucket="schemacms-pages"),
                upload_to=schemacms.utils.models.file_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("embed_video", "Embed Video"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("embed_video", "Embed Video"),
                ],
                max_length=25,
            ),
        ),
    ]
