# Generated by Django 2.2.10 on 2020-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0041_auto_20200608_0649"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblockelement",
            name="state",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="blocktemplateelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("embed_video", "Embed Video"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("state", "State"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("connection", "Connection"),
                    ("custom_element", "Custom Element"),
                    ("embed_video", "Embed Video"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("internal_connection", "Internal Connection"),
                    ("markdown", "Markdown"),
                    ("observable_hq", "ObservableHQ"),
                    ("plain_text", "Plain Text"),
                    ("state", "State"),
                ],
                max_length=25,
            ),
        ),
    ]
