# Generated by Django 2.2.10 on 2020-06-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0005_auto_20200527_0703"),
        ("pages", "0043_remove_pageblockelement_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblockelement",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elements",
                to="states.State",
            ),
        ),
    ]
