# Generated by Django 2.2.10 on 2020-06-18 13:45
from django.db import transaction
from django.db import migrations


def add_names_to_custom_elements(apps, schema_editor):
    element = apps.get_model("pages", "PageBlockElement")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        for ele in element.objects.using(db_alias).filter(custom_element_set__isnull=False):
            if ele.name is None:
                ele.name = ele.type
                ele.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0044_pageblockelement_state"),
    ]

    operations = [
        migrations.RunPython(add_names_to_custom_elements),
    ]
