# Generated by Django 2.2.10 on 2020-06-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0047_auto_20200624_0809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="page_blocks", to="pages.Page"
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="observable_hq",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.PageBlockObservableElement"
            ),
        ),
    ]
