# Generated by Django 2.2.10 on 2020-07-29 20:38

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0048_auto_20200629_0749"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_draft",
            field=models.BooleanField(db_index=True, default=True, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="published_version",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_version",
                to="pages.Page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "draft"),
                    ("published", "published"),
                    ("waiting_to_republish", "waiting to republish"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
