# Generated by Django 2.2.10 on 2020-06-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0048_auto_20200626_0639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblockelement",
            name="observable_hq",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.PageBlockObservableElement"
            ),
        ),
    ]
