# Generated by Django 2.2.10 on 2020-07-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0049_auto_20200730_0701"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblock",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
