# Generated by Django 2.2.10 on 2020-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0051_auto_20200730_1252"),
    ]

    operations = [
        migrations.AddField(model_name="page", name="link", field=models.URLField(blank=True, default=""),),
    ]
