# Generated by Django 2.2.13 on 2020-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0052_page_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="section", name="is_rss_content", field=models.BooleanField(default=False),
        ),
    ]
