# Generated by Django 2.2.13 on 2020-09-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_section_is_rss_content'),
        ('pages', '0053_auto_20200910_0944'),
    ]

    operations = [
    ]
