# Generated by Django 2.2.13 on 2020-09-14 08:35
from django.db import migrations, models, transaction


def set_publish_date_for_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    db_alias = schema_editor.connection.alias

    publish_states = ["published", "waiting_to_republish"]
    with transaction.atomic():
        for page in Page.objects.using(db_alias).filter(
            is_draft=False, is_template=False, state__in=publish_states
        ):
            page.publish_date = page.modified
            page.draft_version.publish_date = page.modified
            page.save(update_fields=["publish_date"])
            page.draft_version.save(update_fields=["publish_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0054_merge_20200910_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="page", name="publish_date", field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_publish_date_for_page, migrations.RunPython.noop),
    ]
