# Generated by Django 2.2.13 on 2020-10-07 08:21

from django.db import migrations, models, transaction


def set_is_main_page(apps, schema_editor):
    Section = apps.get_model("pages", "Section")

    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        for section in Section.objects.using(db_alias).all():
            if section.main_page:
                page = section.main_page
                page.is_main_page = True
                page.save(update_fields=["is_main_page"])


def set_section_main_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        for page in Page.objects.using(db_alias).filter(is_main_page=True, is_draft=True, is_template=False):
            page.section.main_page = page
            page.section.save(update_fields=["main_page"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0055_page_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="page", name="is_main_page", field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_main_page, set_section_main_page),
        migrations.RemoveField(model_name="section", name="main_page",),
    ]
