# Generated by Django 2.2.13 on 2020-10-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0058_auto_20201009_1528"),
    ]

    operations = [
        migrations.RemoveField(model_name="pageblockelement", name="internal_connection",),
    ]
