# Generated by Django 2.2.13 on 2020-10-29 14:33

from django.db import migrations, models
import schemacms.utils.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0060_pageblockelement_internal_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageblockelement",
            name="file",
            field=models.FileField(
                max_length=200,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(bucket="schemacms-pages"),
                upload_to=schemacms.utils.models.file_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="pageblockelement",
            name="image",
            field=models.ImageField(
                max_length=200,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(bucket="schemacms-pages"),
                upload_to=schemacms.utils.models.file_upload_path,
            ),
        ),
    ]
