# Generated by Django 2.2.13 on 2021-10-25 07:18

from django.db import migrations, models
import schemacms.utils.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_auto_20201029_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='social_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='social_image',
            field=models.ImageField(max_length=200, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='schemacms-pages'), upload_to=schemacms.utils.models.file_upload_path),
        ),
        migrations.AddField(
            model_name='page',
            name='social_image_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='social_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
