import os


HOST = os.getenv("LOCALSTACK_HOSTNAME", '')

AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv(
    'AWS_S3_ENDPOINT_URL',
    f"http://{HOST}:4572"
)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_DEFAULT_REGION = os.getenv('AWS_DEFAULT_REGION')
SECRET_MANAGER_ENDPOINT_URL = os.getenv(
    'SECRET_MANAGER_ENDPOINT_URL',
    f"http://{HOST}:4584"
)
LAMBDA_AUTH_TOKEN = os.getenv('LAMBDA_AUTH_TOKEN', '')

BACKEND_URL = os.getenv('BACKEND_URL', '')
