# Generated by Django 2.2.10 on 2020-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="tagcategory", name="unique_tag_category_name",),
        migrations.AddConstraint(
            model_name="tagcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at=None),
                fields=("name", "project"),
                name="unique_tag_category_name",
            ),
        ),
    ]
