# Generated by Django 2.2.10 on 2020-05-13 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_auto_20200508_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagcategory",
            name="type",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
