# Generated by Django 2.2.10 on 2020-05-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_tagcategory_type"),
    ]

    operations = [
        migrations.RenameField(model_name="tagcategory", old_name="is_public", new_name="is_available",),
    ]
