# Generated by Django 2.2.10 on 2020-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0005_auto_20200519_0900"),
    ]

    operations = [
        migrations.AlterField(model_name="tagcategory", name="name", field=models.CharField(max_length=100),),
    ]
