# Generated by Django 2.2.10 on 2020-06-08 08:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import schemacms.tags.models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0006_auto_20200527_0703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagcategory",
            name="type",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=schemacms.tags.models.default_category_type
            ),
        ),
    ]
