# Generated by Django 2.1.9 on 2019-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('undefined', 'undefined'), ('admin', 'admin'), ('editor', 'editor')], default='undefined', max_length=25),
        ),
    ]
