# Generated by Django 2.1.9 on 2019-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('undefined', 'undefined'), ('auth0', 'auth0')], default='undefined', max_length=16),
        ),
    ]
