# Generated by Django 2.1.9 on 2019-08-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='role',
        ),
    ]
