version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - OLDPATH=$(pwd)
  build:
    commands:
      - echo Build lambda public_api function package
      - mkdir -p backend/functions/build
      - cd backend/functions/public_api
      - npm install && node_modules/serverless/bin/serverless package
      - unzip .serverless/public-api.zip -d ${OLDPATH}/backend/functions/build
  post_build:
    commands:
      - cd ${OLDPATH}
artifacts:
  name: lambda-public-api
  files:
    - '**/*'
  base-directory: backend/functions/build
