version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - pip install pipenv
      - echo install AWS CDK...
      - make install-infra-cdk
      - VERSION=$(cat VERSION)
      - echo "Build version:$VERSION"
  build:
    commands:
      - echo Build started on `date`
      - echo Synchesize CDK stack...
      - cd infra
      - pipenv run node_modules/.bin/cdk synth -c app_image_tag=$VERSION
artifacts:
  files:
    - './infra/cdk.out/**/*'
  name: cdk-out
cache:
  paths:
    - '/root/.npm/**/*'
    - '.env'
