version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - pip install pipenv
      - echo install AWS CDK...
      - make install-infra-cdk
      - cdk --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION=${COMMIT_HASH:=latest}
      - echo "Build version:$VERSION"
  build:
    commands:
      - echo Build started on `date`
      - echo Synchesize CDK stack...
      - cd infra
      - pipenv run cdk synth -c app_image_tag=$VERSION
artifacts:
  files:
    - 'cdk.out/**/*'
  name: cdk-out
cache:
  paths:
    - '/root/.npm/**/*'
    - '.env'
