version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - OLDPATH=$(pwd)
  build:
    commands:
      - echo Build lambda scheduler package
      - mkdir -p backend/functions/build
      - cd backend/functions/worker
      - npm install && node_modules/.bin/sls package
      - unzip .serverless/main.zip -d ${OLDPATH}/backend/functions/build
  post_build:
    commands:
      - cd ${OLDPATH}
artifacts:
  name: lambda-scheduler
  files:
    - '**/*'
  base-directory: backend/functions/build
