name: CI

on:
  push:
    branches: [ feature/CI-CD-update  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - shell: bash
        env:
          CODE_COMMIT_REPO: ${{ secrets.CODE_COMMIT_REPO }}
        run: |
          git remote add codecommit "$CODE_COMMIT_REPO"
          git push -u codecommit ${GITHUB_REF#refs/heads/}
          git push codecommit --tags
